### ISSUE TITLE
CLI doesn't work with inputs having multiple items as a default

### ISSUE THREAD

**Issue by JuhaKiili** [valohai/valohai-cli#145]
valohai.yaml having an input with multiple default items
```
- step:
    name: test
    image: python:3.7
    - name: myinput
      default:
      - https://upload.wikimedia.org/wikipedia/en/a/a9/Example.jpg
      - https://homepages.cae.wisc.edu/~ece533/images/airplane.png
```

Running
```
vh exec run -a test
```
Aborts with:
```
API Error: Internal error
```

According to @akx the bug is caused by: "the list of default inputs gets transformed into a single string"
