### ISSUE TITLE
vh yaml step command destroys custom command(s), environment and image for a step on update

### ISSUE THREAD

**Issue by JuhaKiili** [valohai/valohai-cli#149]
If you have:
```
- step:
    name: train
    image: tensorflow/tensorflow:2.4.0-gpu
    environment: azure-westeurope-nc6
    command:
    - apt-get update
    - apt-get install -y wget libsm6 libxext6 libxrender-dev
    - pip install -r /valohai/repository/requirements-gpu.txt
    - python convert.py --weights /valohai/inputs/weights/yolov3.weights --output
      ./checkpoints/yolov3.tf
    - python train.py {parameters} --classes /valohai/inputs/classes/classes.txt --weights
      ./checkpoints/yolov3.tf --dataset /valohai/inputs/dataset/train.tfrecord --val_dataset
      /valohai/inputs/dataset/train.tfrecord
```

And you update it with (say adding extra parameter)
```
vh yaml step train.py
```

You end up with:
```
- step:
    name: train
    image: python:3.7
    command:
    - pip install -r requirements.txt
    - python ./train.py {parameters}
```

Image, environment and command are all gone. The update should be incremental instead, just adding the new extra parameter and leaving the rest as is.
