### ISSUE TITLE
vh lint doesn't understand indentation errors

### ISSUE THREAD

**Issue by DrazenDodik** [valohai/valohai-cli#153]
`vh lint` throws an error if the valohai.yaml file has lines that are not properly indented.

The error message is cryptic:
`error:   Type validation on pipeline: None is not of type 'object' (2.pipeline)`

The error message should clearly say that the issue is in indentation.

Below an example of a pipeline that fails. But if you indent everything under pipeline (lineno 2->) it's valid.

```yaml
- pipeline:
  name: mypipeline
  nodes:
    - name: validation-node
      type: task
      step: validate
    - name: ingest-node
      type: task
      step: ingest
      override:
      inputs:
          - name: image
  edges:
    - [validation-node.parameter.image, ingest-node.parameter.image]
```
