### ISSUE TITLE
vh pipeline run fails if no default input data is provided

### ISSUE THREAD

**Issue by DrazenDodik** [valohai/valohai-cli#160]
Running `vh pipeline run mypipeline` sends an invalid API request to Valohai if you don't provide a default value for your input.

It looks like if there is no default value for an input set valohai-utils will send:
```
        "inputs": {
          "data": null
        },
```
instead of 
```
        "inputs": {
          "data": []
        },
```
`valohai.yaml` to reproduce:
```
- step:
    name: preprocessing
    image: tensorflow/tensorflow:2.4.1
    command: echo "hello" > /valohai/outputs/data_transformed.txt
- step:
    name: train
    image: tensorflow/tensorflow:2.4.1
    command: echo "moi"
    inputs:
      - name: data
        default: "s3://onboard-sample/tf-sample/mnist.npz"
        optional: true
- pipeline:
    name: mypipeline
    edges:
      - configuration: {}
        source: preprocessing_1.output.data_transformed.txt
        target: train_1.input.data
    nodes:
      - name: preprocessing_1
        override: {}
        actions: []
        step: preprocessing
        type: execution
      - name: train_1
        override: {}
        actions: []
        step: train
        type: execution
```

When launching from the UI the API call is:
```
{
  "edges": [
    {
      "source_node": "preprocessing_1",
      "source_key": "data_transformed.csv",
      "source_type": "output",
      "target_node": "train_1",
      "target_type": "input",
      "target_key": "data"
    }
  ],
  "nodes": [
    {
      "name": "preprocessing_1",
      "type": "execution",
      "template": {
        "commit": "9f3dc349417e67d5ba49b4eb77cdfc9bbd756451",
        "step": "preprocessing",
        "image": "tensorflow/tensorflow:2.4.1",
        "command": "echo \"hello\" > /valohai/outputs/data_transformed.csv",
        "inputs": {},
        "parameters": {},
        "runtime_config": {
          "type": "vm"
        },
        "inherit_environment_variables": true,
        "time_limit": 0,
        "environment_variables": {}
      },
      "actions": []
    },
    {
      "name": "train_1",
      "type": "execution",
      "template": {
        "commit": "9f3dc349417e67d5ba49b4eb77cdfc9bbd756451",
        "step": "train",
        "image": "tensorflow/tensorflow:2.4.1",
        "command": "echo \"moi\"",
        "inputs": {
          "data": []
        },
        "parameters": {},
        "runtime_config": {
          "type": "vm"
        },
        "inherit_environment_variables": true,
        "time_limit": 0,
        "environment_variables": {}
      },
      "actions": []
    }
  ],
  "project": "...",
  "title": "mypipeline"
}
```

When launching from CLI the API call is:
```
{
  "edges": [
    {
      "source_node": "preprocessing_1",
      "source_key": "data_transformed.csv",
      "source_type": "output",
      "target_node": "train_1",
      "target_type": "input",
      "target_key": "data"
    }
  ],
  "nodes": [
    {
      "name": "preprocessing_1",
      "type": "execution",
      "template": {
        "commit": "9f3dc349417e67d5ba49b4eb77cdfc9bbd756451",
        "step": "preprocessing",
        "image": "tensorflow/tensorflow:2.4.1",
        "command": "echo \"hello\" > /valohai/outputs/data_transformed.csv",
        "inputs": {},
        "parameters": {},
        "inherit_environment_variables": true,
        "environment_variables": {}
      }
    },
    {
      "name": "train_1",
      "type": "execution",
      "template": {
        "commit": "9f3dc349417e67d5ba49b4eb77cdfc9bbd756451",
        "step": "train",
        "image": "tensorflow/tensorflow:2.4.1",
        "command": "echo \"moi\"",
        "inputs": {
          "data": null
        },
        "parameters": {},
        "inherit_environment_variables": true,
        "environment_variables": {}
      }
    }
  ],
  "project": "....",
  "title": "mypipeline"
}
```
