### ISSUE TITLE
Exec run messes multi parameters

### ISSUE THREAD

**Issue by tokkoro** [valohai/valohai-cli#211]
When a step parameter is configured in valohai YAML with following properties
```yaml
name: "list-param"
default: ["one","two","three"]
multiple: separate
```
It should convert into a JSON payload with `exec run` command
```json
"parameters": {"list-param": ["one","two","three"]}
```
But currently it converts to 
```json
"parameters": {"list-param": "['one','two','three']"}
```
that is then end up in command as
```shell
python ./train.py '--list-param=['"'"'one'"'"', '"'"'two'"'"', '"'"'three'"'"']'
```
Related to https://github.com/valohai/roi/issues/3118
