### ISSUE TITLE
Allow using lists for pipeline parameters form the CLI

### ISSUE THREAD

**Issue by noorula** [valohai/valohai-cli#300]
I have a list type parameter
```
    parameters:
        - name: dataset_names
          default: [all_harbors]
          type: string
          multiple: separate
          multiple-separator: ','
          optional: false
```

and I want to use pipeline parameter to assign its values. 
```
- pipeline:
    name: training-pipeline
    parameters:
      - name: dataset
        targets:
          - preprocess.parameter.dataset_names
        default: [all_harbors, harbor_A]
```

If I commit the code and run in the UI it works fine but for adhoc runs I get this error on the CLI:

```
API Error:
parameters:
  dataset:
    expression:
      * Incorrect pipeline parameter. Expected ParameterExpression, string, int, float, or bool but got ['all_harbors', 'harborA'] (code: invalid)
```
